site_name: "Bubble | Документация"
docs_dir: '../../ru'
site_dir: '../../generated/ru'
theme:
  name: material
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue
      accent: blue
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue
      accent: blue
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  language: ru
extra:
  alternate:
    - name: English
      link: /en/ 
      lang: en
    - name: Русский
      link: /ru/
      lang: ru